<?xml version="1.0" encoding="utf-8"?><Database Name="BankDatabase" Class="DatabaseMappingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\bin\Debug\Database\Schema\BankDatabase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Server.Properties.Settings" SettingsPropertyName="BankDatabaseConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Number" Type="System.String" DbType="NChar(26) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Customer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_History" Member="Histories" ThisKey="Number" OtherKey="AccountNumber" Type="History" />
      <Association Name="Customer_Account" Member="Customer1" ThisKey="Customer" OtherKey="Id" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Account" Member="Accounts" ThisKey="Id" OtherKey="Customer" Type="Account" />
    </Type>
  </Table>
  <Table Name="dbo.History" Member="Histories">
    <Type Name="History">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountNumber" Type="System.String" DbType="NChar(26) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ConnectedAccount" Type="System.String" DbType="NChar(26)" CanBeNull="true" />
      <Column Name="OperationType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Account_History" Member="Account" ThisKey="AccountNumber" OtherKey="Number" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
</Database>